library(SheetReader)
options(stringsAsFactors = FALSE)
data <- read_xlsx(system.file("extdata", "multi-test.xlsx", package = "SheetReader"), sheet="escape")
stopifnot(colnames(data) == c("Escape", "This"))
stopifnot(data[1, "This"] == "&")
stopifnot(data[2, "This"] == "'")
stopifnot(data[3, "This"] == "\"")
stopifnot(data[4, "This"] == ">")
stopifnot(data[5, "This"] == "<")
stopifnot(data[6, "This"] == "What is < than \"\" & '>'")
