# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_xlsx <- function(path, sheet = NULL, headers = TRUE, skip_rows = 0L, skip_columns = 0L, num_threads = -1L, col_types = NULL) {
    .Call(`_SheetReader_read_xlsx`, path, sheet, headers, skip_rows, skip_columns, num_threads, col_types)
}

