# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_xlsx <- function(path, sheet = NULL, headers = TRUE, skip_rows = 0L, skip_columns = 0L, method = "efficient", num_threads = -1L) {
    .Call(`_SheetReader_read_xlsx`, path, sheet, headers, skip_rows, skip_columns, method, num_threads)
}

